package com.bmwanje.audiophile.vocalremover

import org.jtransforms.fft.FloatFFT_1D
import kotlin.math.PI
import kotlin.math.cos

/**
 * Host-side STFT/iSTFT for the UVR MDX-Net ONNX model.
 *
 * The implementation mirrors the UVR MDX-Net contract:
 *   - periodic Hann window;
 *   - n_fft/model-specific hop;
 *   - center=True time padding;
 *   - one-sided spectrum n_fft/2+1;
 *   - crop to dimF for the network;
 *   - zero-pad the cropped spectrum back to n_fft/2+1 before iSTFT.
 *
 * The caller is responsible for the UVR-style outer chunk margin:
 * each model chunk contains n_fft/2 samples of left/right context and only
 * chunkSize - n_fft samples are emitted from its center.
 *
 * Contract:
 *   input  = stereo PCM, 44.1 kHz, exactly chunkSizeSamples() per channel
 *   tensor = [1,4,dimF,dimT] flattened as [L_re,L_im,R_re,R_im]
 */
class MdxStft(private val spec: MdxModelSpec) {
    companion object {
        const val SAMPLE_RATE = 44_100
        const val MODEL_INPUT_CHANNELS = 4
    }

    private val n = spec.nFft
    private val dimF = spec.dimF
    private val hop = spec.hop
    private val dimT = spec.dimT
    private val centerPad = n / 2
    private val chunkSize = hop * (dimT - 1)
    private val generatedSamples = chunkSize - 2 * centerPad
    private val nBins = n / 2 + 1
    private val tensorSize = MODEL_INPUT_CHANNELS * dimF * dimT

    private val window = FloatArray(n) { i ->
        // torch.hann_window(periodic=true)
        (0.5 - 0.5 * cos(2.0 * PI * i.toDouble() / n.toDouble())).toFloat()
    }
    private val windowSq = FloatArray(n) { i ->
        val w = window[i]
        w * w
    }
    private val fft = FloatFFT_1D(n.toLong())

    init {
        require(n % 2 == 0) { "MDX FFT size must be even" }
        require(dimF in 1 until nBins) {
            "dimF=$dimF must be smaller than one-sided bin count $nBins"
        }
        require(dimT >= 2) { "dimT must be at least 2" }
        require(generatedSamples > 0) {
            "MDX chunk does not contain a positive central generation region"
        }
    }

    data class Spectrogram(val data: FloatArray) {
        init {
            require(data.isNotEmpty())
        }
    }

    data class StereoChunk(val left: FloatArray, val right: FloatArray) {
        init {
            require(left.size == right.size)
        }

        val size: Int
            get() = left.size
    }

    fun chunkSizeSamples(): Int = chunkSize

    /** n_fft/2 samples of context are excluded at each side of a UVR chunk. */
    fun edgeTrimSamples(): Int = centerPad

    /** Number of source samples generated by one complete MDX chunk. */
    fun generatedSamplesPerChunk(): Int = generatedSamples

    fun tensorSize(): Int = tensorSize

    fun forward(left: FloatArray, right: FloatArray): Spectrogram {
        require(left.size == chunkSize && right.size == chunkSize) {
            "Expected $chunkSize samples per channel"
        }

        val out = FloatArray(tensorSize)
        writeChannel(left, out, planeBase = 0)
        writeChannel(right, out, planeBase = 2)
        return Spectrogram(out)
    }

    private fun writeChannel(
        input: FloatArray,
        out: FloatArray,
        planeBase: Int,
    ) {
        // torch.stft(..., center=True, pad_mode='reflect') performs a
        // reflect-pad of n_fft/2 on both sides before framing.
        val padded = reflectPad(input)
        val frame = FloatArray(2 * n)
        val realBase = planeBase * dimF * dimT
        val imagBase = (planeBase + 1) * dimF * dimT

        for (t in 0 until dimT) {
            val start = t * hop
            for (i in 0 until n) {
                frame[i] = padded[start + i] * window[i]
            }
            java.util.Arrays.fill(frame, n, 2 * n, 0f)

            fft.realForwardFull(frame)

            // The UVR model only receives the lowest dimF one-sided bins.
            for (k in 0 until dimF) {
                out[realBase + k * dimT + t] =
                    finite(frame[2 * k])
                out[imagBase + k * dimT + t] =
                    finite(frame[2 * k + 1])
            }
        }
    }

    fun inverse(spectrogram: Spectrogram): StereoChunk {
        require(spectrogram.data.size == tensorSize) {
            "Expected tensor size $\{tensorSize}, got $\{spectrogram.data.size}"
        }

        val left = inverseChannel(spectrogram.data, 0)
        val right = inverseChannel(spectrogram.data, 2)
        return StereoChunk(left, right)
    }

    private fun inverseChannel(
        specData: FloatArray,
        planeBase: Int,
    ): FloatArray {
        /*
         * UVR concatenates [dimF bins] with zeros up to n_fft/2+1 bins, then
         * performs a centered iSTFT. Build that full complex spectrum explicitly
         * for JTransforms' realInverseFull().
         */
        val accum = FloatArray(chunkSize + 2 * centerPad)
        val envelope = FloatArray(chunkSize + 2 * centerPad)
        val frame = FloatArray(2 * n)

        val realBase = planeBase * dimF * dimT
        val imagBase = (planeBase + 1) * dimF * dimT

        for (t in 0 until dimT) {
            java.util.Arrays.fill(frame, 0f)

            // Copy the model's retained one-sided bins. Bins dimF..nBins-1
            // are the explicit UVR zero-frequency pad.
            for (k in 0 until dimF) {
                frame[2 * k] =
                    finite(specData[realBase + k * dimT + t])
                frame[2 * k + 1] =
                    finite(specData[imagBase + k * dimT + t])
            }

            // A real-valued time signal has real DC and Nyquist bins.
            frame[1] = 0f
            frame[2 * (n / 2) + 1] = 0f

            // Reconstruct the negative-frequency half. The omitted high positive
            // bins are already zero, matching UVR's zero-padding before iSTFT.
            for (k in 1 until n / 2) {
                val src = 2 * k
                val dst = 2 * (n - k)
                frame[dst] = frame[src]
                frame[dst + 1] = -frame[src + 1]
            }

            fft.realInverseFull(frame, true)

            val start = t * hop
            for (i in 0 until n) {
                val x = frame[i] * window[i]
                accum[start + i] += x
                envelope[start + i] += windowSq[i]
            }
        }

        /*
         * center=True removes n_fft/2 samples at both edges. At the same time,
         * overlap/add is normalized by the sum of squared windows, matching the
         * least-squares normalization used by torch.istft().
         */
        val out = FloatArray(chunkSize)
        for (i in 0 until chunkSize) {
            val index = i + centerPad
            val denom = envelope[index]
            out[i] =
                if (denom > 1.0e-8f) {
                    finite(accum[index] / denom)
                } else {
                    0f
                }
        }
        return out
    }

    private fun reflectPad(input: FloatArray): FloatArray {
        val out = FloatArray(input.size + 2 * centerPad)
        System.arraycopy(input, 0, out, centerPad, input.size)

        // Match torch's reflect padding: endpoint samples themselves are not
        // repeated.
        for (j in 0 until centerPad) {
            out[j] = input[centerPad - j]
            out[centerPad + input.size + j] =
                input[input.size - 2 - j]
        }
        return out
    }

    private fun finite(value: Float): Float =
        if (value.isFinite()) value else 0f
}
